namespace Fesh;

// The real animals behind the Fish log (1.16): for a real species its scientific name and a few true things about it;
// for one made up for the game, the real relative it's based on. Shown on a fish's card under its picture once you've
// caught it or seen it get away. Keep each one short enough for the card's box (the autotest measures them all).
static class FishFacts
{
    // Real: the game's fish is a real animal (Sci is its scientific name). Otherwise Sci names the real relative.
    public sealed record Fact(string Sci, string Text, bool Real = true);

    static Fact Made(string basedOn, string text) => new(basedOn, text, false);

    public static readonly Dictionary<string, Fact> ById = new()
    {
        // Amihan
        ["bangus"] = new("Chanos chanos", "Often called the national fish of the Philippines. Farmed in brackish ponds for centuries, it grazes on algae, including the \"lab-lab\" mat that grows on pond floors. Wild adults spawn out at sea and can grow longer than 1.5 m."),
                ["banak"] = new("Family Mugilidae", "Mullets live along warm coasts all around the world, from the open sea up into rivers. They sift mud and algae for food. Schools often leap clear of the water, and nobody is quite sure why."),
        ["kitang"] = new("Scatophagus argus", "Its scientific name means \"dung eater\", from its habit of feeding near harbour drains. Spotted scats live in mangroves and estuaries, and the spines on their fins carry a mild venom that stings."),
        ["asohos"] = new("Sillago sihama", "Silver sillago sweep sandy shallows for worms and tiny crabs, and dive into the sand to hide when a predator comes near. They live from the Red Sea to the western Pacific."),
        ["lapu_lapu"] = new("Epinephelus spp.", "Many groupers start life as females and turn into males as they grow bigger. They are ambush hunters that gulp their prey whole. Prized in the live reef fish trade, several kinds are now overfished."),
        ["maya_maya"] = new("Lutjanus spp.", "Snappers are named for their strong jaws and sharp canine teeth. Red snappers hunt fish, shrimp and crabs around reefs and rocky bottoms, and some kinds live for decades."),
        ["talakitok"] = new("Caranx spp.", "Trevallies are powerful reef hunters. The biggest, the giant trevally, can top 1.7 m and 80 kg, and in the Seychelles it has been filmed leaping out of the water to snatch young seabirds."),
                ["hito"] = new("Clarias spp.", "Hito are air-breathing catfish: a branching organ above the gills lets them gulp air, so they survive in muddy, oxygen-poor water. The native Philippine hito has become scarce, while African catfish brought in for farming are now common."),
                ["dalag"] = new("Channa striata", "The striped snakehead breathes air and can last through the dry season buried in damp mud. The parents guard their eggs and their swarm of orange fry. Where people have released it outside its home range, it can harm native fish."),
        ["amihan_mudskipper"] = new("Periophthalmus spp.", "Mudskippers are gobies that spend much of their lives out of the water. They carry water in their gill chambers, breathe through their skin and walk on their front fins. Males dig burrows and leap high to show off."),
        ["tanigue"] = new("Scomberomorus commerson", "The narrow-barred Spanish mackerel is a fast, toothy hunter of sardines and squid that can grow over 2 m long. It is a favourite for kinilaw, and it is listed as Near Threatened because so many are caught."),
        ["yellowfin_tuna"] = new("Thunnus albacares", "Yellowfin tuna roam warm oceans all over the world and can reach 200 kg. General Santos City on Mindanao calls itself the Tuna Capital of the Philippines, and many of its yellowfin are caught on a single handline."),
        ["amihan_barracuda"] = new("Sphyraena barracuda", "The great barracuda waits perfectly still, then bursts forward to grab its prey. It can grow to about 2 m. Eating a big reef barracuda can cause ciguatera, a poisoning from toxins that build up along the food chain."),
        ["galunggong"] = new("Decapterus spp.", "Galunggong, the round scads, travel in huge schools and have long been the everyday fish on Filipino tables. Overfishing cut catches so badly that a three-month closed season now protects them while they spawn off northern Palawan."),
        ["tulingan"] = new("Auxis rochei", "Bullet tuna are among the smallest tunas, rarely longer than 50 cm, and they swim in big schools near the surface. Larger fish and seabirds hunt them. In Batangas they are slow-cooked into sinaing na tulingan."),
        ["pating"] = new("Carcharhinus limbatus", "Blacktip sharks hunt schools of small fish in coastal seas, sometimes charging up through a school so fast that they spin out of the water. They grow to about 2.5 m, have few young, and are listed as Vulnerable."),
        ["malasugi"] = new("Makaira nigricans", "Female blue marlin can weigh several hundred kilos, far more than the males. Marlin slash through schools of fish with their bills to stun their prey, and their stripes light up electric blue when they're excited."),
        // Saltmere
        ["pond_perch"] = Made("European perch, Perca fluviatilis", "Its look comes from the European perch: green with dark bars and orange-red fins. Perch hunt in small groups, and they're one of the first fish many young anglers in Europe and northern Asia catch."),
        ["mud_carp"] = new("Cirrhinus molitorella", "The real mud carp comes from rivers in southern China and Vietnam, where it grazes algae and scraps off the bottom. Farmers raise it in ponds alongside other carps, each kind feeding at a different depth."),
        ["moon_carp"] = Made("Common carp, Cyprinus carpio", "There's no moon carp, but the moon really does matter to fish. Many reef fish, and corals too, time their spawning to the phases of the moon."),
        ["old_whiskers"] = Made("Wels catfish, Silurus glanis", "Many carp and catfish have \"whiskers\", called barbels, that taste and feel for food in muddy water. One of the biggest whiskered fish is the wels catfish of Europe, which can grow longer than 2.5 m."),
        ["rock_goby"] = new("Gobius paganellus", "The rock goby lives in rock pools and under stones on the shores of Europe and the Mediterranean. Like other gobies, its pelvic fins are joined into a little sucker that helps it hold on in the surf."),
        ["striped_wrasse"] = Made("Bluestreak cleaner wrasse, Labroides dimidiatus", "Based on the cleaner wrasse, which runs \"cleaning stations\" on coral reefs. Big fish, even groupers and moray eels, wait their turn and open their mouths so it can pick off parasites."),
        ["rusty_grouper"] = Made("Atlantic goliath grouper, Epinephelus itajara", "Groupers love the shelter of shipwrecks. The Atlantic goliath grouper can top 300 kg and gathers at wrecks to spawn. It was fished almost to nothing, and it has been protected in US waters since 1990."),
        ["barnacle_bass"] = Made("European sea bass, Dicentrarchus labrax", "Barnacles really do hitch rides on slow swimmers, but mostly on whales, sea turtles and crabs rather than fish. The real bass of rocky Atlantic coasts is the European sea bass."),
        ["storm_eel"] = Made("Electric eel, Electrophorus spp.", "Electric fish are real. South America's electric eel, which is really a knifefish and not a true eel, can stun its prey with shocks of up to 860 volts."),
        ["silver_tuna"] = Made("Tunas, Thunnus spp.", "Real tunas are built for speed. They fold their fins into grooves along the body to cut drag, and a web of blood vessels keeps their swimming muscles warmer than the sea around them."),
                ["lantern_squid"] = new("Family Lycoteuthidae", "Real lantern squids live in the deep sea, with light organs around their eyes and along their bodies. Their cousin the firefly squid lights up Toyama Bay in Japan each spring, when millions rise to spawn."),
        ["shore_crab"] = new("Carcinus maenas", "The European green crab is a tough shore crab that has spread around the world in ships' ballast water. It is now an invasive pest in North America, Australia and South Africa, where it eats young clams and mussels."),
        // Frostfang
        ["arctic_char"] = new("Salvelinus alpinus", "The Arctic char lives farther north than any other freshwater fish, in icy lakes and rivers around the Arctic. Some go to sea to feed each summer, and spawning males turn bright orange-red."),
        ["frost_smelt"] = Made("Rainbow smelt, Osmerus mordax", "Based on the rainbow smelt. Freshly caught smelt really do smell of cucumber, and in winter people fish for them through holes in the ice."),
        ["crystal_pike"] = Made("Northern pike, Esox lucius", "The northern pike is an ambush hunter of cold lakes, with a mouth full of teeth that point backwards. For see-through fish, look to the glass catfish of Thailand, so clear you can see its skeleton."),
        ["polar_cod"] = new("Boreogadus saida", "The polar cod lives farther north than any other fish, hiding in cracks under the sea ice. Antifreeze proteins in its blood keep it from freezing. Real ones are small, rarely over 30 cm, and seals, whales and seabirds depend on them."),
        ["snow_crab"] = new("Chionoecetes opilio", "Snow crabs live on cold, muddy sea floors in the North Atlantic and North Pacific. Billions vanished from the Bering Sea after a marine heatwave, and in 2022 Alaska cancelled its snow crab season for the first time."),
        ["aurora_trout"] = new("Salvelinus fontinalis timagamiensis", "The aurora trout is a rare form of brook trout from two lakes in Ontario, Canada. Acid rain wiped out the wild fish by the late 1960s; a few saved in a hatchery were bred and put back once the lakes recovered."),
        ["king_crab"] = new("Paralithodes camtschaticus", "Red king crabs can span 1.8 m from leg tip to leg tip, and they're closer kin to hermit crabs than to true crabs. Brought to the Barents Sea by Soviet scientists in the 1960s, they have spread along Norway's coast."),
                ["blind_cavefish"] = new("Astyanax mexicanus", "The Mexican blind cavefish is the same species as a river fish with eyes. In the dark caves its eyes start to grow in the embryo, then shrink away under the skin, and it finds food with sense organs along its sides that feel the water move."),
        ["glow_shrimp"] = Made("Deep-sea shrimp, Acanthephyra spp.", "Some real deep-sea shrimp can spit out a cloud of glowing liquid to dazzle a hunter while they slip away into the dark."),
        ["ghost_eel"] = Made("Freshwater eels, Anguilla spp.", "Young freshwater eels really are see-through. These \"glass eels\" drift in from the ocean after hatching far out at sea, then turn dark as they swim up rivers. The European eel is now critically endangered."),
        ["abyssal_lanternfish"] = new("Family Myctophidae", "Lanternfish are small deep-sea fish with rows of lights along the body. There are trillions of them, and each night many swim hundreds of metres up to feed, then sink again by dawn: one of the biggest daily migrations on Earth."),
                ["pale_cave_shark"] = Made("Nurse shark, Ginglymostoma cirratum", "No shark spends its whole life in a cave, but nurse sharks and whitetip reef sharks often rest in sea caves by day and come out to hunt at night."),
        ["ancient_coelacanth"] = new("Latimeria chalumnae", "Coelacanths were known only from fossils and thought to have died out 66 million years ago, until one turned up in a fishing net off South Africa in 1938. They rest in deep rocky caves and can live for about a century."),
        // Sunscald
        ["oasis_tilapia"] = new("Oreochromis spp.", "Tilapia come from Africa and the Middle East. The mothers of many kinds carry their eggs and babies in their mouths to keep them safe. Today tilapia are farmed in more than 100 countries, the Philippines among them."),
        ["desert_pupfish"] = new("Cyprinodon macularius", "The desert pupfish lives in springs and marshes of the Sonoran Desert, in water that can be hotter than 40 degrees C and saltier than the sea. It is endangered; its cousin the Devils Hole pupfish lives in a single flooded cave in Nevada."),
        ["mirage_koi"] = new("Cyprinus rubrofuscus", "Koi are colourful carp bred in Japan since the 1800s, starting with rice farmers in Niigata. With good care they can live for over 50 years, and a champion koi has sold for more than a million US dollars."),
        ["sunscale_lungfish"] = new("Protopterus annectens", "African lungfish breathe air with real lungs. When their pools dry up they burrow into the mud and wrap themselves in a cocoon of slime, waiting months or even years for rain. Lungfish are the closest living fish relatives of four-legged animals, us included."),
        ["sun_mackerel"] = Made("Atlantic mackerel, Scomber scombrus", "Its wavy back comes from the Atlantic mackerel, whose tiger stripes help hide it from hunters above. The Atlantic mackerel has no swim bladder, so it has to keep swimming or slowly sink."),
        ["sand_ray"] = Made("Stingrays, family Dasyatidae", "Stingrays flap sand over their backs until only their eyes show. Holes behind the eyes, called spiracles, let a buried ray breathe without sucking in sand. Shuffle your feet when you wade, so they swim off instead of stinging."),
        ["thunderfin"] = Made("Blacktip shark, Carcharhinus limbatus", "Fish may sense storms coming. In Florida, young blacktip sharks were tracked swimming out to deeper water as the air pressure dropped before a tropical storm."),
        ["ghost_crab"] = new("Ocypode spp.", "Ghost crabs dig burrows on sandy beaches and are among the fastest crabs, which is why they seem to vanish. Their eyes sit on tall stalks, and the Atlantic ghost crab growls at rivals using teeth inside its stomach."),
        // Mirewood
        ["mudskipper"] = new("Periophthalmus spp.", "Mudskippers can stay out of the water for hours, rolling in mud to keep their skin wet. They even blink, pulling their eyes down into wet cups in their heads, a trick that evolved apart from ours."),
        ["swamp_catfish"] = Made("Catfish, order Siluriformes", "Many real catfish \"talk\". They grunt by drumming on their swim bladder, or creak by rubbing the spine of a front fin in its socket."),
        ["emerald_arowana"] = Made("Asian arowana, Scleropages formosus", "The silver arowana of the Amazon leaps up to 2 m out of the water to snatch insects from branches. Its cousin, the green Asian arowana, is prized as a lucky fish, and wild ones are endangered."),
        ["mire_leviathan"] = Made("Arapaima, Arapaima gigas", "Arapaima are among the biggest freshwater fish, reaching about 3 m. They must rise to gulp air every few minutes, and their scales are tough enough to stop a piranha's bite. Lakes guarded by local villages in Brazil have brought them back."),
        ["parrotfish"] = new("Family Scaridae", "Parrotfish scrape algae off coral with a beak made of fused teeth, grind up the bits of rock, and poop them out as fine white sand: a big one makes hundreds of kilos a year. Many sleep inside a bubble of mucus they blow around themselves."),
        ["jungle_piranha"] = new("Pygocentrus nattereri", "Red-bellied piranhas have razor teeth, but their man-eating fame is mostly a myth. They eat fish, insects, snails and plants, and swim in shoals mainly to stay safe from their own hunters. They even bark when caught."),
        ["crayfish"] = new("Infraorder Astacidea", "Crayfish are freshwater cousins of lobsters. Tasmania's giant freshwater crayfish can weigh over 4 kg, the biggest freshwater invertebrate in the world. Others dig mud chimneys down to the water in swamps."),
        // Starfall
        ["clownfish"] = new("Amphiprion ocellaris", "Clownfish live among stinging sea anemones, kept safe by a special slime on their skin. They start life neither male nor female. The biggest in each anemone is the female and the next biggest her mate; if she dies, he turns female and takes her place."),
        ["moorish_idol"] = new("Zanclus cornutus", "The Moorish idol is the only species in its family. Its trailing fin and black, white and yellow bars stand out on Indo-Pacific reefs, but it rarely does well in aquariums because it lives on sponges."),
        ["pearl_angelfish"] = Made("Marine angelfish, family Pomacanthidae", "Many angelfish change their colours completely as they grow. Young emperor angelfish wear blue and white rings that look nothing like the yellow stripes of the adults."),
                ["silver_moonfish"] = Made("Moonfish, Mene maculata", "Based on the moonfish, a razor-thin silver disc of Indo-Pacific coasts and the only living member of its family. Rising for the full moon is the game's idea."),
        ["bluefin_tuna"] = new("Thunnus thynnus", "Bluefin tuna can weigh over 600 kg and keep their bodies much warmer than the sea, so they can hunt in cold water. Prized for sushi, they were badly overfished; strict catch limits have helped them recover."),
        ["sailfish"] = new("Istiophorus platypterus", "Sailfish raise their huge sail-like fin to herd sardines into a tight ball, then slash with their bills to injure fish. They're often called the fastest fish in the sea, though the famous 110 km/h figure is probably too high."),
        ["golden_marlin"] = Made("Marlins, family Istiophoridae", "There's no golden marlin, but marlins do change colour: when they hunt or are hooked, cells in their skin can make their stripes light up blue in an instant."),
        ["giant_squid"] = new("Architeuthis dux", "Giant squid can reach about 12 m with their long feeding tentacles, and their eyes, as big as dinner plates, are among the largest in the animal kingdom. No one filmed a live one in the deep sea until 2012."),
        ["starfall_ray"] = Made("Giant manta ray, Mobula birostris", "Giant mantas can be 7 m across and have some of the largest brains of any fish. Each has its own pattern of spots on its belly, which scientists use to tell them apart. They are endangered."),
        ["seafoam_goby"] = Made("Gobies, family Gobiidae", "Gobies are one of the biggest fish families, with around 2,000 kinds. The dwarf pygmy goby of the Philippines is one of the smallest fish known, only about 1 cm long when fully grown."),
        ["blue_hole_grouper"] = Made("Giant grouper, Epinephelus lanceolatus", "The giant grouper is the biggest bony fish on coral reefs: it can pass 2.5 m and 400 kg, and it swallows spiny lobsters, small sharks and even young sea turtles whole."),
        ["moonglass_fish"] = Made("Glass catfish, Kryptopterus vitreolus", "See-through fish are real. The glass catfish of Thailand has almost no colour in its skin or muscles, so you can see right through to its bones."),
        ["spiny_lobster"] = new("Panulirus spp.", "Spiny lobsters have no big claws. They defend themselves with spines and by rubbing their feelers to make a loud rasp. Caribbean spiny lobsters even migrate across the sea floor in single-file lines."),
        // The open sea
        ["flying_fish"] = new("Family Exocoetidae", "Flying fish don't flap. They speed up underwater, burst out and spread their wing-like fins to glide. By dipping their tails to push off again, they can stay in the air for over 40 seconds."),
        ["mahi_mahi"] = new("Coryphaena hippurus", "Mahi-mahi, also called dolphinfish (they aren't dolphins), grow very fast and seldom live more than four or five years. They gather under floating logs and seaweed, and their bright colours fade soon after they're caught."),
        ["swordfish"] = new("Xiphias gladius", "Swordfish dive hundreds of metres into cold, dark water to hunt. A special organ by their eyes warms them, giving sharper sight in the cold. The flat sword slashes prey rather than spearing it."),
        ["ocean_sunfish"] = new("Mola mola", "The ocean sunfish is one of the heaviest bony fish, at up to about 2 tonnes. A female can carry around 300 million eggs. It basks on its side at the surface, perhaps to warm up after deep dives, while birds pick off its parasites."),
        ["ironbill"] = Made("Black marlin, Istiompax indica", "The black marlin is one of the biggest bony fish: the record on a rod and reel is 707 kg, caught off Peru in 1953. Unlike other marlins, its pectoral fins are stiff and can't fold flat against its body."),
        ["alimasag_crab"] = new("Portunus pelagicus", "Blue swimming crabs paddle with flat, oar-like back legs. In the Philippines they support many small-scale fishers, and much of the crab meat is exported; rules protect small crabs and egg-carrying females."),
        // Habagat
        ["danggit"] = new("Siganus spp.", "Rabbitfish graze seagrass and algae like rabbits nibbling grass. The spines on their fins carry venom, so handle them with care. Split, salted and sun-dried, they become danggit, a famous breakfast from Cebu."),
        ["sapsap"] = new("Family Leiognathidae", "Ponyfish are coated in slime, which is why they feel so slippery. Many glow: bacteria in an organ around the throat make light that hides their shadow from hunters below. Their mouths shoot out like a tube to suck up food."),
        ["pagi"] = new("Taeniura lymma", "The bluespotted ribbontail ray hunts worms, shrimp and crabs on sandy patches near reefs, moving into the shallows on the rising tide. Its tail carries venomous spines, used only in self-defence, usually when it's stepped on."),
        ["labahita"] = new("Acanthurus spp.", "Surgeonfish are named for the scalpel-sharp spine on each side of the tail, which they flick out in a fight. They spend the day grazing algae, which helps keep it from smothering the coral."),
        ["bisugo"] = new("Nemipterus spp.", "Threadfin breams live over sandy and muddy bottoms, feeding on shrimp, crabs and small fish. Several kinds trail a long thread from the tail fin, which gives them their name."),
        ["pugita"] = new("Octopus spp.", "Octopuses have three hearts, blue blood, and most of their nerve cells in their arms. They can change colour and skin texture in an instant, and they can squeeze through any gap bigger than their beak."),
        ["tamban"] = new("Sardinella spp.", "Sardines like tamban strain plankton from the water and travel in huge shoals. They're the heart of Zamboanga's canning industry, and closed seasons in Zamboanga and the Visayan Sea let them spawn in peace."),
        ["pusit"] = new("Sepioteuthis lessoniana", "Bigfin reef squid have fins along almost their whole body. They are drawn to light at night, so fishers hang lamps over the water to catch them. Most live for less than a year."),
        ["buan_buan"] = new("Megalops cyprinoides", "The Indo-Pacific tarpon can gulp air at the surface with a lung-like swim bladder, so it survives in stale, still water. Its babies are see-through, ribbon-shaped larvae like those of eels."),
                ["haring_buan"] = Made("Atlantic tarpon, Megalops atlanticus", "The Indo-Pacific tarpon rarely grows past a metre. A king-sized one is a legend, but its Atlantic cousin, the \"silver king\", really does reach about 2.5 m, with big silver scales and famous leaps when hooked."),
        ["alumahan"] = new("Rastrelliger kanagurta", "Indian mackerel swim with their mouths wide open, straining plankton through long gill rakers. They're one of the most important small fish sold in Philippine markets."),
        ["matang_baka"] = new("Selar crumenophthalmus", "The bigeye scad's huge eyes help it hunt shrimp and small fish at night. Schools come close to shore, where they're caught with lights and nets. In Hawaii it's called akule."),
        ["talang_talang"] = new("Scomberoides spp.", "Queenfish are silvery jacks with tough, leathery skin. Young queenfish feed on the scales of other fish, a strange start for a fish that grows into a strong hunter and a spectacular jumper."),
        ["dalagang_bukid"] = new("Caesio cuning", "Fusiliers are quick, schooling plankton-eaters of the reef's edge. At night they shelter in the reef and their colours turn reddish. The redbelly yellowtail fusilier is a common fish in Philippine markets."),
        ["salay_salay"] = new("Selaroides leptolepis", "The yellowstripe scad is a small jack of shallow coastal waters, seldom longer than 20 cm. Its schools feed on tiny shrimp and plankton over sandy and muddy bottoms."),
        ["alimango_crab"] = new("Scylla serrata", "Mud crabs live in mangroves, digging burrows in the mud. Their big crushing claws can crack snail shells. Young crabs are gathered and fattened in ponds, so losing mangroves means losing mud crabs."),
        ["curacha_crab"] = new("Ranina ranina", "The spanner crab, or red frog crab, buries itself backwards in sand with only its eyes showing and grabs passing prey. In Zamboanga it's steamed and served as curacha with Alavar sauce."),
        ["sugpo_shrimp"] = new("Penaeus monodon", "The giant tiger prawn can grow over 30 cm. Much of the Philippines' mangrove forest was cleared for fish and shrimp ponds in the last century, which is one reason replanting mangroves matters today.")
    };
}
