<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Fesh</RootNamespace>
    <AssemblyName>Fesh</AssemblyName>
    <Product>Fesh</Product>
    <Version>1.6.0</Version>
    <ApplicationIcon>Assets\fesh.ico</ApplicationIcon>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Raylib-cs" Version="8.1.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\Fonts\*.ttf" LogicalName="%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
